site_name: pypilot_mfd
site_author: Sean D'Epagnier
repo_url: https://github.com/pypilot/pypilot_doc
copyright: GPLv3

plugins:
  - with-pdf:
      output_path: pdf/pypilot_mfd_user_manual.pdf
      cover_subtitle: Official pypilot MFD User Manual
