site_name: pypilot
site_author: Sean D'Epagnier
repo_url: https://github.com/pypilot/pypilot_doc
copyright: GPLv3

plugins:
  - with-pdf:
      output_path: pdf/pypilot_user_manual.pdf
      cover: true
      cover_subtitle: Official pypilot User Manual
      #      cover_logo: docs/img/favicon.png
      #      custom_template_path: cover_page.tpl
